const pagePanel = document.querySelector('#panel');
const languageButton = document.querySelector('.language-switch');
const pageIds = ['about', 'services', 'contract', 'contact'];
const chinesePages = Object.fromEntries(pageIds.map((id) => [id, document.querySelector(`#${id}`).innerHTML]));

const legalPage = document.createElement('article');
legalPage.id = 'legal'; legalPage.className = 'page legal-page'; legalPage.hidden = true;
pagePanel.append(legalPage);

const englishPages = {
  about: `<section class="about-mondrian" aria-label="About Our Friday Goldfish Studio"><h2 class="about-title">About Our Friday Goldfish Studio</h2><div class="about-grid"><section class="mondrian-cell about-white about-intro"><p>Our Friday Goldfish Studio is a graphic design studio based in the Netherlands. We take on cover, poster, graphic design, and book design projects.</p></section><section class="mondrian-cell about-red"><p>Research, publishing<br />and visual expression.</p></section><section class="mondrian-cell about-yellow"><p>Let ideas<br />swim together here.</p></section><section class="mondrian-cell about-white about-invoice"><p>We can issue invoices and have long-term collaborations with doctoral groups at well-known Dutch universities. Doctoral candidates may submit cover-design costs for reimbursement through their group.</p></section><section class="mondrian-cell about-blue"><p class="about-eyebrow">WHY “OUR FRIDAY GOLDFISH”?</p><h3>Some names arrive first;<br />their meanings swim in later.</h3><p class="about-quote" lang="en">"Put any two random words together and there's a 70% chance it's a band name, and a 30% chance it means absolutely nothing."</p><p>Our Friday Goldfish Studio grew from this joke. Our design process does much the same: it notices chance connections among research, words, colours and objects, then turns them into a clear, moving expression through concept, typography and imagery.</p></section><div class="mondrian-cell about-black" aria-hidden="true"></div></div><p class="about-hint">HOVER THE COLOUR BLOCKS · SCROLL TO SHIFT THE COMPOSITION</p></section>`,
  services: `<p class="label">02 / SERVICES</p><h2>Design services</h2><div class="price"><b>€300</b><span>DESIGN SERVICE FEE</span></div><p><strong>Design service fee: €300</strong></p><p>The thesis package includes complete design and pre-print adjustments:</p><ul><li>Front cover, back cover and spine</li><li>Thesis defence invitation</li><li>A text-free cover visual, suitable as a presentation title-slide background</li><li>All formatting adjustments before print submission</li></ul><p>Additional services, such as <strong>thesis interior layout</strong>, can be quoted separately according to chapter count.</p><h3>Timeline</h3><p>The schedule is planned backwards from the final print-shop or digital-submission deadline.</p><p>A standard project takes about <strong>3–4 weeks</strong>. For urgent deadlines, a <strong>rush route is available at no extra charge</strong>, with first delivery possible in around <strong>one week</strong>. The shorter discussion period may naturally allow less time for refinement.</p><h3>Payment</h3><p><strong>Private payment: €300</strong><br />Paid in two stages: €100 deposit + €200 balance on delivery.</p><p><strong>Research group / project budget: €490 invoice</strong><br />This can be reimbursed through a doctoral group or project budget. About €190 of the invoice covers taxes paid to the government; <strong>the designer’s actual service income remains €300, the same as for private payment.</strong></p>`,
  contract: `<p class="label">03 / AGREEMENT</p><h2>Clear terms make<br />a good beginning.</h2><p>Complete the form below to automatically download the bilingual design-service agreement.</p><div class="contract-form"><iframe data-tally-src="https://tally.so/embed/q4lEkO?alignLeft=1&hideTitle=1&transparentBackground=1&dynamicHeight=1" loading="lazy" width="100%" height="580" frameborder="0" marginheight="0" marginwidth="0" title="Design service agreement download form"></iframe></div>`,
  contact: `<p class="label">04 / CONTACT</p><h2>Let us hear<br />your idea.</h2><p>Please include your <strong>research topic and expected deadline</strong>. If you already have visual preferences, reference images, a stylistic direction or first ideas are also very welcome—they help us understand your needs faster.</p><div class="contact-list"><p>WeChat: <button type="button" class="wechat-link" data-wechat-qr>SyrupTablets</button></p><p>WhatsApp: <a href="https://wa.me/8615882410847" target="_blank" rel="noopener">+86 15882410847 ↗</a></p><p>RED: 金鱼游过星期五</p><a href="mailto:ourfridaygoldfish@gmail.com">Email: ourfridaygoldfish@gmail.com ↗</a><p>Phone: +31 6 14296059</p></div>`
};

const legalCopy = {
  zh: `<p class="label">LEGAL / PRIVACY</p><h2>隐私、Cookie 与版权说明</h2><h3>隐私</h3><p>Our Friday Goldfish Studio（“OFG Studio”）负责处理本网站相关的个人信息。联系方式：<a href="mailto:ourfridaygoldfish@gmail.com">ourfridaygoldfish@gmail.com</a>。</p><p>当你通过邮件、微信或其他沟通渠道联系工作室时，我们可能处理你主动提供的姓名、联系方式、研究／项目资料与沟通内容。用途仅限回复咨询、制作报价、履行设计服务、开具发票及保存必要的项目记录。处理依据可能包括为签约或履约所必需、你的同意、法定义务或工作室的正当利益。</p><p>咨询资料通常保存不超过 12 个月；合同、发票和项目记录会依照适用的荷兰税务与法律保存要求留存。我们不会出售你的个人信息。网站托管或邮件服务商可能在提供服务所需范围内处理数据。</p><p>你可请求查阅、更正、删除、限制处理、数据可携带或反对处理，也可向荷兰数据保护机构 Autoriteit Persoonsgegevens 投诉。请先通过上述邮箱联系我们。</p><h3>Cookie 与本地存储</h3><p>目前网站不使用广告、分析或社交媒体追踪 Cookie。语言选择仅保存在你的浏览器本地存储中，以便下次访问时保持语言偏好。若未来添加分析、营销 Cookie 或嵌入式第三方服务，我们会先更新本说明，并在法律要求时取得同意。</p><h3>版权</h3><p>除另有书面说明外，本网站的文字、版式、图像、设计概念、草稿与最终作品的著作权均归 OFG Studio 或相应权利人所有。客户付清费用后获得合同约定用途内的使用许可；未经书面许可，不得复制、再发布、改编或将未付款、退款、取消项目的设计成果交由第三方继续制作。</p><p>客户须确保其提供的文字、图片、Logo 与其他素材已获合法授权。作品展示会尽量隐去个人信息；如需移除已展示作品，请通过邮箱联系。</p><p class="legal-note">本页面为网站基础说明，并非针对个案的法律意见。上线表单、分析工具或广告服务前，应按实际工具和数据流程复核本说明。</p>`,
  en: `<p class="label">LEGAL / PRIVACY</p><h2>Privacy, cookies and copyright</h2><h3>Privacy</h3><p>Our Friday Goldfish Studio (“OFG Studio”) is responsible for personal data related to this website. Contact: <a href="mailto:ourfridaygoldfish@gmail.com">ourfridaygoldfish@gmail.com</a>.</p><p>When you contact the studio by email, WeChat or another channel, we may process the name, contact details, research or project material, and correspondence you provide. We use it only to respond to enquiries, prepare quotations, deliver design services, issue invoices and keep necessary project records. The relevant basis may be steps toward or performance of a contract, consent, a legal obligation, or OFG Studio’s legitimate interests.</p><p>Enquiry material is normally kept for no longer than 12 months. Agreements, invoices and project records may be retained for periods required by applicable Dutch tax and legal rules. We do not sell personal data. Hosting and email providers may process data only as needed to provide their services.</p><p>You may request access, rectification, erasure, restriction, data portability or object to processing. You may also lodge a complaint with the Dutch data protection authority, Autoriteit Persoonsgegevens. Please contact us first using the email above.</p><h3>Cookies and local storage</h3><p>This website currently does not use advertising, analytics or social-media tracking cookies. Your language choice is saved only in your browser’s local storage so it can persist on your next visit. If analytics, marketing cookies or embedded third-party services are added later, this notice will be updated and consent will be requested where required.</p><h3>Copyright</h3><p>Unless agreed otherwise in writing, copyright in this website’s text, layouts, images, concepts, drafts and final works belongs to OFG Studio or the relevant rights holder. After full payment, a client receives a licence for the agreed purpose only. Unpaid, refunded or cancelled work may not be copied, republished, adapted or passed to another party for completion without written permission.</p><p>Clients are responsible for ensuring that their supplied text, images, logos and other assets are lawfully licensed. Portfolio displays aim to remove personal information; contact us by email if a displayed project should be reviewed for removal.</p><p class="legal-note">This page is a practical website notice, not legal advice for a particular situation. Review it against the actual tools and data flows before adding forms, analytics or advertising services.</p>`
};

const navigationLabels = { zh: ['关于 OFG', '服务', '合同下载', '联系'], en: ['About OFG', 'Services', 'Agreement', 'Contact'] };
const footer = document.querySelector('footer');
const legalLink = document.createElement('button'); legalLink.className = 'footer-legal'; footer.append(' · ', legalLink);

const showPage = (id) => { pagePanel.hidden = false; document.querySelectorAll('.page').forEach((page) => { page.hidden = page.id !== id; }); document.body.style.overflow = 'hidden'; };
legalLink.addEventListener('click', () => showPage('legal'));

const applyLanguage = (language) => {
  window.ofgLanguage = language;
  localStorage.setItem('ofg-language', language);
  document.documentElement.lang = language === 'en' ? 'en' : 'zh-CN';
  pageIds.forEach((id) => { document.querySelector(`#${id}`).innerHTML = language === 'en' ? englishPages[id] : chinesePages[id]; });
  legalPage.innerHTML = legalCopy[language];
  document.querySelectorAll('.nav-links [data-page]').forEach((button, index) => { button.textContent = navigationLabels[language][index]; });
  languageButton.innerHTML = language === 'en' ? '中文 / <b>EN</b>' : '<b>中文</b> / EN';
  languageButton.title = language === 'en' ? '切换至中文' : 'Switch to English';
  legalLink.textContent = language === 'en' ? 'PRIVACY / LEGAL' : '隐私／法律';
  const wechatDialog = document.querySelector('.wechat-qr-dialog');
  if (wechatDialog) {
    wechatDialog.querySelector('img').alt = language === 'en' ? 'WeChat QR code for SyrupTablets' : 'SyrupTablets 的微信二维码';
    wechatDialog.querySelector('p').textContent = language === 'en' ? 'Scan in WeChat to add SyrupTablets' : '微信扫码添加 SyrupTablets';
    wechatDialog.querySelector('a').textContent = language === 'en' ? 'Save QR code ↓' : '保存二维码 ↓';
    wechatDialog.querySelector('.wechat-qr-close').setAttribute('aria-label', language === 'en' ? 'Close QR code' : '关闭二维码');
  }
  footer.firstChild.textContent = language === 'en' ? '© 2026 OUR FRIDAY GOLDFISH STUDIO · AMSTERDAM, THE NETHERLANDS' : '© 2026 OUR FRIDAY GOLDFISH STUDIO · 阿姆斯特丹，荷兰';
  document.title = language === 'en' ? 'Our Friday Goldfish Studio' : 'Our Friday Goldfish Studio｜平面设计事务所';
  window.refreshOpenProjectLanguage?.();
};
languageButton.addEventListener('click', () => applyLanguage(window.ofgLanguage === 'en' ? 'zh' : 'en'));
applyLanguage(localStorage.getItem('ofg-language') === 'en' ? 'en' : 'zh');
