(() => {
  const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const face=(id,part)=>`assets/books/${encodeURIComponent('拆分封面封底')}/${['p31','p32'].includes(id)?id.toUpperCase()+'%20'+part:id+'-'+(id==='p21'&&part==='spine'?'spin':part)}.jpg`;
  const textures=['linen','vertical-ribbed','cotton-pulp','coated','book-cloth','lychee-leather','debossed-board'];
  const textureFor=id=>textures[(Math.max(1,parseInt(String(id).replace(/\D/g,''),10)||1)-1)%textures.length];
  const decorateShelf=()=>document.querySelectorAll('.book[data-project]').forEach(book=>{book.dataset.texture=textureFor(book.dataset.project)});
  const shelf=document.querySelector('#track');if(shelf){decorateShelf();new MutationObserver(decorateShelf).observe(shelf,{childList:true,subtree:true})}
  let dispose;
  window.openProject=project=>{
    dispose?.();
    const returnFocus=document.activeElement,oldOverflow=document.body.style.overflow,en=document.documentElement.lang==='en',translated=en?window.ofgEnglishProjects?.[project.id]:null;
    const title=project.title?translated?.title||project.title.split(/[｜丨|]/).pop():'',body=translated?.body||project.body;
    const room=document.createElement('section');room.className='reading-room';room.dataset.state='inspect';room.dataset.texture=textureFor(project.id);room.style.visibility='hidden';room.setAttribute('role','dialog');room.setAttribute('aria-modal','true');room.setAttribute('aria-label',title||(en?'Private commission':'私密作品'));
    room.innerHTML=`<header class="reading-top"><div>OFG / READING ROOM<small>OUR FRIDAY GOLDFISH · ${esc(project.id.toUpperCase())}</small></div><button class="reading-close" aria-label="${en?'Close book':'合上书，返回书架'}">×</button></header><div class="reading-inspect" tabindex="0" role="button" aria-label="${en?'Rotate book; click again to open':'旋转查看书籍；再次点击打开'}"><div class="reading-prism" aria-hidden="true"><div class="prism-face prism-front"></div><div class="prism-face prism-back"></div><div class="prism-face prism-spine"></div><div class="prism-face prism-edge"></div><div class="prism-face prism-top"></div><div class="prism-face prism-bottom"></div></div></div><div class="reading-inspect-actions"><p>${en?'DRAG TO INSPECT · CLICK THE BOOK AGAIN TO READ':'拖动旋转查看 · 再次点击书本开始阅读'}</p><button data-open-book>${en?'Open book':'打开阅读'} →</button></div><div class="reading-volume" aria-hidden="true"><div class="reading-page reading-left"></div><div class="reading-page reading-right"></div><div class="reading-cover" aria-hidden="true"><div class="reading-cover-front"></div><div class="reading-cover-inside"></div></div></div><nav class="reading-controls" aria-label="${en?'Book pages':'翻页'}"><button data-prev>←</button><span class="reading-status" aria-live="polite"></span><button data-next>→</button></nav><div class="reading-hint">${en?'TURN THE PAGES · ARROW KEYS OR SWIPE':'点击箭头或左右滑动翻页'}</div>`;
    document.body.append(room);document.body.style.overflow='hidden';const site=document.querySelector('main'),wasInert=site?.inert;if(site)site.inert=true;
    const volume=room.querySelector('.reading-volume'),inspect=room.querySelector('.reading-inspect'),prism=room.querySelector('.reading-prism'),left=room.querySelector('.reading-left'),right=room.querySelector('.reading-right'),cover=room.querySelector('.reading-cover'),prev=room.querySelector('[data-prev]'),next=room.querySelector('[data-next]'),openButton=room.querySelector('[data-open-book]'),status=room.querySelector('.reading-status');
    const frontUrl=face(project.id,'front'),spineUrl=face(project.id,'spine');[volume,prism].forEach(el=>{el.style.setProperty('--cover-colour',project.color);el.style.setProperty('--cover-image',`url("${frontUrl}")`);el.style.setProperty('--back-image',`url("${face(project.id,'back')}")`);el.style.setProperty('--spine-image',`url("${spineUrl}")`);});
    let pages=[],index=0,busy=false,timer,resizeTimer,state='inspect',rotX=-7,rotY=24,pointer=null,suppressClick=false,swipe,pageRatio=.7,spineRatio=22/580;
    const reduced=()=>matchMedia('(prefers-reduced-motion:reduce)').matches,setState=s=>{state=s;room.dataset.state=s;},setRotation=()=>prism.style.transform=`rotateX(${rotX}deg) rotateY(${rotY}deg)`;setRotation();
    const mobile=()=>matchMedia('(max-width:600px)').matches,stride=()=>mobile()?1:2,content=(html,n)=>`<div class="reading-page-inner">${html||''}</div><div class="reading-folio"><span>OFG STUDIO</span><span>${n==null?'':String(n+1).padStart(2,'0')}</span></div>`;
    function setGeometry(){const small=mobile(),maxW=innerWidth*(small ? .84 : .44),maxH=innerHeight*(small ? .68 : .70),h=Math.min(maxH,maxW/pageRatio),w=h*pageRatio,d=h*spineRatio;room.style.setProperty('--page-w',`${w}px`);room.style.setProperty('--page-h',`${h}px`);room.style.setProperty('--spread-w',`${small ? w : w*2}px`);room.style.setProperty('--book-d',`${d}px`);room.dataset.depth=d.toFixed(2)}
    function paginate(){pages=[];if(title)pages.push(`<p class="reading-kicker">${esc(project.id.toUpperCase())} / COVER STORIES</p><h2>${esc(title)}</h2><p class="reading-kicker">${esc(project.published||'')}</p>`);const measure=document.createElement('div');measure.className='reading-page reading-measure';measure.innerHTML='<div class="reading-page-inner"><p class="reading-text"></p></div>';volume.append(measure);const area=measure.firstElementChild,p=area.firstElementChild;let text=Array.from(body||'');while(text.length){let lo=1,hi=text.length,best=1;while(lo<=hi){const mid=(lo+hi)>>1;p.textContent=text.slice(0,mid).join('');if(p.scrollHeight<=area.clientHeight-4){best=mid;lo=mid+1}else hi=mid-1}if(best<text.length)for(let n=best;n>best*.7;n--)if(/[。！？.!?\n]/.test(text[n-1])){best=n;break}pages.push(`<p class="reading-text">${esc(text.splice(0,best).join(''))}</p>`)}measure.remove();(project.images||[]).forEach((src,n)=>pages.push(`<figure><img src="${esc(src)}" alt="${esc(title||project.id)} — ${n+1}"><figcaption>${String(n+1).padStart(2,'0')} / ${en?'ARTWORK':'作品画面'}</figcaption></figure>`));index=Math.min(index,Math.max(0,pages.length-1));index-=index%stride()}
    function render(){left.innerHTML=content(mobile()?'':pages[index],index);right.innerHTML=content(pages[index+(mobile()?0:1)],index+(mobile()?0:1));prev.disabled=index===0||busy;next.disabled=busy||index+stride()>=pages.length;status.textContent=`${index+1}${!mobile()&&index+1<pages.length?'–'+Math.min(index+2,pages.length):''} / ${pages.length}`}
    function open(){if(state!=='inspect'||busy)return;busy=true;setState('opening');inspect.setAttribute('aria-disabled','true');openButton.disabled=true;rotX=0;rotY=Math.round(rotY/360)*360;prism.classList.add('is-aligning');setRotation();timer=setTimeout(()=>{inspect.hidden=true;volume.hidden=false;volume.setAttribute('aria-hidden','false');paginate();render();requestAnimationFrame(()=>requestAnimationFrame(()=>volume.classList.add('is-open')));timer=setTimeout(()=>{cover.hidden=true;busy=false;setState('reading');render();next.focus({preventScroll:true})},reduced()?0:1400)},reduced()?0:620)}
    function turn(d){if(state!=='reading'||busy)return;const target=index+d*stride();if(target<0||target>=pages.length)return;busy=true;render();const leaf=document.createElement('div');leaf.className='reading-leaf';const old=index;leaf.innerHTML=`<div class="reading-page">${content(pages[d>0?old+(mobile()?0:1):target+(mobile()?0:1)],null)}</div><div class="reading-page reading-leaf-back">${content(pages[d>0?target:old],null)}</div>`;if(d<0)leaf.style.transform='rotateY(-180deg)';volume.append(leaf);index=target;if(d>0)right.innerHTML=content(pages[target+(mobile()?0:1)],target+(mobile()?0:1));else left.innerHTML=content(pages[target],target);requestAnimationFrame(()=>requestAnimationFrame(()=>leaf.style.transform=d>0?'rotateY(-180deg)':'rotateY(0deg)'));timer=setTimeout(()=>{leaf.remove();busy=false;render()},reduced()?0:780)}
    const close=()=>dispose?.(),key=e=>{if(e.key==='Escape'){e.preventDefault();close()}else if(state==='inspect'&&(e.key==='Enter'||e.key===' ')&&(e.target===inspect||e.target===openButton)){e.preventDefault();open()}else if(e.key==='ArrowRight'){e.preventDefault();state==='inspect'?(rotY+=8,setRotation()):turn(1)}else if(e.key==='ArrowLeft'){e.preventDefault();state==='inspect'?(rotY-=8,setRotation()):turn(-1)}else if(state==='inspect'&&e.key==='ArrowUp'){e.preventDefault();rotX=Math.max(-25,rotX-5);setRotation()}else if(state==='inspect'&&e.key==='ArrowDown'){e.preventDefault();rotX=Math.min(25,rotX+5);setRotation()}else if(e.key==='Tab'){const controls=[...room.querySelectorAll('button:not(:disabled),[tabindex="0"]')].filter(el=>el.getClientRects().length);if(e.shiftKey&&document.activeElement===controls[0]){e.preventDefault();controls.at(-1).focus()}else if(!e.shiftKey&&document.activeElement===controls.at(-1)){e.preventDefault();controls[0].focus()}}},resize=()=>{clearTimeout(resizeTimer);resizeTimer=setTimeout(()=>{setGeometry();if(state==='reading'&&!busy){paginate();render()}},180)};
    dispose=()=>{clearTimeout(timer);clearTimeout(resizeTimer);window.removeEventListener('keydown',key);window.removeEventListener('resize',resize);room.remove();if(site)site.inert=wasInert;document.body.style.overflow=oldOverflow;returnFocus?.focus({preventScroll:true});dispose=null};room.querySelector('.reading-close').onclick=close;prev.onclick=()=>turn(-1);next.onclick=()=>turn(1);openButton.onclick=open;prev.setAttribute('aria-label',en?'Previous pages':'上一页');next.setAttribute('aria-label',en?'Next pages':'下一页');
    inspect.addEventListener('pointerdown',e=>{if(state!=='inspect'||e.button>0)return;pointer={id:e.pointerId,x:e.clientX,y:e.clientY,lastX:e.clientX,lastY:e.clientY,dragged:false,threshold:e.pointerType==='touch'?10:7};inspect.setPointerCapture(e.pointerId)});inspect.addEventListener('pointermove',e=>{if(!pointer||pointer.id!==e.pointerId)return;if(Math.hypot(e.clientX-pointer.x,e.clientY-pointer.y)>=pointer.threshold)pointer.dragged=true;if(pointer.dragged){rotY+=(e.clientX-pointer.lastX)*.55;rotX=Math.max(-25,Math.min(25,rotX-(e.clientY-pointer.lastY)*.4));setRotation()}pointer.lastX=e.clientX;pointer.lastY=e.clientY});inspect.addEventListener('pointerup',e=>{if(!pointer||pointer.id!==e.pointerId)return;const activate=!pointer.dragged;pointer=null;suppressClick=true;e.preventDefault();if(activate)open()});inspect.addEventListener('click',e=>{if(suppressClick){suppressClick=false;e.preventDefault();return}if(e.detail===0)open()});const cancel=()=>pointer=null;inspect.addEventListener('pointercancel',cancel);inspect.addEventListener('lostpointercapture',cancel);
    volume.style.touchAction='pan-y';volume.addEventListener('pointerdown',e=>swipe={x:e.clientX,y:e.clientY});volume.addEventListener('pointerup',e=>{if(swipe&&Math.abs(e.clientX-swipe.x)>45&&Math.abs(e.clientX-swipe.x)>Math.abs(e.clientY-swipe.y))turn(e.clientX<swipe.x?1:-1);swipe=null});volume.addEventListener('pointercancel',()=>swipe=null);window.addEventListener('keydown',key);window.addEventListener('resize',resize);volume.hidden=true;const probe=url=>new Promise(resolve=>{const img=new Image();img.onload=()=>resolve(img);img.onerror=()=>resolve(null);img.src=url});Promise.all([probe(frontUrl),probe(spineUrl)]).then(([frontImage,spineImage])=>{if(frontImage?.naturalWidth&&frontImage?.naturalHeight)pageRatio=frontImage.naturalWidth/frontImage.naturalHeight;if(spineImage?.naturalWidth&&spineImage?.naturalHeight)spineRatio=spineImage.naturalWidth/spineImage.naturalHeight;setGeometry();room.style.visibility='';openButton.focus({preventScroll:true})})
  };
})();
